### ISSUE TITLE
Race condition when deleting labels

### ISSUE THREAD

**Issue by seemethere** [seemethere/release-bot#13]
Related to: https://github.com/docker/release-tracking/issues/186#issuecomment-344653176.

Appears like the bot is having a race condition where the label being removed is triggering the bot to remove the card from the project, which then triggers all labels to be removed for that project.

Here’s the logs that apply to that:
```time="2017-11-15T16:35:18Z" level=info msg="/docker/release-tracking Moving issue #186 in project 17.09.1-ce-rc1 from 'Triage' to 'Cherry Pick'"
time="2017-11-15T16:35:18Z" level=info msg="Deleting label 17.09.1-ce/triage for issue docker/release-tracking#186"
time="2017-11-15T16:35:18Z" level=error msg="/docker/release-tracking Move failed for issue #186 in project 17.09.1-ce-rc1 from 'Triage' to 'Cherry Pick':
POST https://api.github.com/projects/columns/cards/5685062/moves: 404 Not Found []"
time="2017-11-15T16:35:18Z" level=info msg="Deleting label 17.09.1-ce/cherry-pick for issue docker/release-tracking#186"
time="2017-11-15T16:35:19Z" level=info msg="Deleting label 17.09.1-ce/cherry-picked for issue docker/release-tracking#186"```

**Comment by seemethere** [comment]
cc @corbin-coleman

**Comment by corbin-coleman** [comment]
This appears to be similar to what I encountered with the transfer cards utility. Too many webhooks getting sent at the same time causing problems. @jose-bigio mentioned using channels could possibly help, but sounds like it might require a large overhaul of the code.

The other option is to just inform people to not add & remove labels at the same time. Just limit their interaction with issues/projects to one command at a time or something. We could just add info to the release-tracking README?

**Comment by seemethere** [comment]
@corbin-coleman I like the documentation approach, let's do that
